"""
Catalog Seed Data
Placeholder/reference battery, inverter, and equipment entries — shaped
to match backend/catalog/models.py (Feature 02 + Feature 11 follow-up),
which uses extra="forbid", so any field not declared on the model will
raise a ValidationError rather than being silently dropped.

Per architecture.md Invariant 6: this is a known-limited seed set, NOT
guaranteed-current market data.
"""

from backend.catalog.models import BatteryCatalog, EquipmentCatalog, InverterCatalog

BATTERY_CATALOG_SEED: list[BatteryCatalog] = [
    BatteryCatalog(
        id="batt_generic_12v_100ah_lifepo4",
        make="generic",
        model="12V 100Ah LiFePO4",
        chemistry="lifepo4",
        nominal_voltage=12,
        capacity_ah=100,
        max_dod_recommended=0.90,
        round_trip_efficiency=0.97,
        peukert_exponent=1.01,
        max_continuous_discharge_amps=100,
    ),
    BatteryCatalog(
        id="batt_generic_12v_200ah_flooded",
        make="generic",
        model="12V 200Ah Flooded Lead-Acid",
        chemistry="flooded_lead_acid",
        nominal_voltage=12,
        capacity_ah=200,
        max_dod_recommended=0.50,
        round_trip_efficiency=0.85,
        peukert_exponent=1.20,
        max_continuous_discharge_amps=40,
    ),
    BatteryCatalog(
        id="batt_generic_6v_225ah_agm",
        make="generic",
        model="6V 225Ah AGM",
        chemistry="agm",
        nominal_voltage=6,
        capacity_ah=225,
        max_dod_recommended=0.60,
        round_trip_efficiency=0.90,
        peukert_exponent=1.12,
        max_continuous_discharge_amps=55,
    ),
    BatteryCatalog(
        id="batt_generic_48v_50ah_lifepo4",
        make="generic",
        model="48V 50Ah LiFePO4 (integrated BMS)",
        chemistry="lifepo4",
        nominal_voltage=48,
        capacity_ah=50,
        max_dod_recommended=0.90,
        round_trip_efficiency=0.97,
        peukert_exponent=1.00,
        max_continuous_discharge_amps=50,
    ),
]

INVERTER_CATALOG_SEED: list[InverterCatalog] = [
    InverterCatalog(
        id="inv_generic_3kva_offgrid",
        make="generic",
        model="3kVA Off-Grid Inverter",
        nominal_dc_voltage=12,
        continuous_va=3000,
        surge_va=6000,
        surge_duration_seconds=5,
        peak_efficiency=0.93,
        waveform="Pure Sine Wave",
        input_voltage_window=[10.5, 15.0],
        lvd_threshold_v=10.5,
        certifications=["IEC62109"],
        grid_tie_capable=False,
    ),
    InverterCatalog(
        id="inv_generic_5kva_hybrid",
        make="generic",
        model="5kVA Hybrid Inverter",
        nominal_dc_voltage=48,
        continuous_va=5000,
        surge_va=10000,
        surge_duration_seconds=5,
        peak_efficiency=0.95,
        waveform="Pure Sine Wave",
        input_voltage_window=[40.0, 60.0],
        lvd_threshold_v=42.0,
        certifications=["IEC62109"],
        grid_tie_capable=True,
    ),
    InverterCatalog(
        id="inv_generic_1kva_budget_modsine",
        make="generic",
        model="1kVA Modified Sine Inverter",
        nominal_dc_voltage=12,
        continuous_va=1000,
        surge_va=1800,
        surge_duration_seconds=3,
        peak_efficiency=0.86,
        waveform="Modified Sine Wave",
        input_voltage_window=[10.5, 15.0],
        lvd_threshold_v=10.5,
        certifications=[],
        grid_tie_capable=False,
    ),
    InverterCatalog(
        id="inv_generic_10kva_gridtie",
        make="generic",
        model="10kVA Grid-Tie Inverter",
        nominal_dc_voltage=96,
        continuous_va=10000,
        surge_va=18000,
        surge_duration_seconds=3,
        peak_efficiency=0.97,
        waveform="Pure Sine Wave",
        input_voltage_window=[90.0, 150.0],
        lvd_threshold_v=90.0,
        certifications=["IEC62109", "UL1741", "IEEE1547"],
        grid_tie_capable=True,
    ),
]

EQUIPMENT_CATALOG_SEED: list[EquipmentCatalog] = [
    EquipmentCatalog(
        id="eq_ac_1_5t_inverter",
        name="Air conditioner (1.5 ton, inverter)",
        category="hvac",
        default_watts=1500,
        default_pf=0.80,
        default_surge_multiplier=4.5,
    ),
    EquipmentCatalog(
        id="eq_led_bulb_9w",
        name="LED bulb (9W)",
        category="lighting_led",
        default_watts=9,
        default_pf=0.70,
        default_surge_multiplier=1.2,
    ),
    EquipmentCatalog(
        id="eq_ceiling_fan",
        name="Ceiling fan",
        category="motor_pump",
        default_watts=75,
        default_pf=0.80,
        default_surge_multiplier=4.0,
    ),
    EquipmentCatalog(
        id="eq_water_pump_1hp",
        name="Water pump (1 HP)",
        category="motor_pump",
        default_watts=750,
        default_pf=0.80,
        default_surge_multiplier=4.0,
    ),
    EquipmentCatalog(
        id="eq_desktop_pc",
        name="Desktop computer + monitor",
        category="electronics_it",
        default_watts=200,
        default_pf=0.85,
        default_surge_multiplier=1.5,
    ),
    EquipmentCatalog(
        id="eq_refrigerator_double_door",
        name="Refrigerator (double door, frost-free)",
        category="motor_compressor",
        default_watts=200,
        default_pf=0.75,
        default_surge_multiplier=5.5,
    ),
    EquipmentCatalog(
        id="eq_electric_geyser_15l",
        name="Electric water heater / geyser (15L)",
        category="heating_resistive",
        default_watts=2000,
        default_pf=1.00,
        default_surge_multiplier=1.0,
    ),
]